{% set name = "evolutionary_keras" %}
{% set version = "2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/N3PDF/evolutionary_keras/archive/v.{{ version }}.tar.gz
  sha256: 9ef71cf220b2af0bac82b538bdadab5a77c65a4f71750d72bfbb8ae2d991c1cc
build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - tensorflow >2.1
    - numpy
    - cma

test:
  imports:
    - evolutionary_keras
  requires:
    - pytest
  commands:
    - pytest --pyargs evolutionary_keras

about:
  home: https://github.com/N3PDF/evolutionary_keras
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: evolution_keras implements Genetic Algorithms for Keras

extra:
  recipe-maintainers:
    - scarlehoff
    - scarrazza
    - roystegeman
